# Vector operation

In [1]:
import numpy as np

In [2]:
u = np.array([2, 4, 5, 6])

In [3]:
2 * u

array([ 4,  8, 10, 12])

In [4]:
v = np.array([1, 0, 0, 2])

In [5]:
u + v

array([3, 4, 5, 8])

# Multiplication

In [9]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [7]:
v.shape[0]

4

In [8]:
v.shape[0]

4

In [11]:
result = vector_vector_multiplication(u, v)

In [12]:
result

np.float64(14.0)

In [13]:
u.dot(v)

np.int64(14)

In [31]:
U = np.array(
    [
        [2,4,5],
        [1,2,1],
        [3,1,2]
    ]
)

In [ ]:
U

array([[2, 4, 5, 6],
       [1, 2, 1, 2],
       [3, 1, 2, 1]])

In [27]:
V = np.array([
    [1, 1, 2],
    [0, 0.5, 1], 
    [0, 2, 1],
])

In [21]:
V

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ],
       [2. , 1. , 0. ]])

In [22]:
def matric_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    num_rows = U.shape[0]
    result = np.zeros(num_rows)
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    return result
    

In [23]:
matric_vector_multiplication(U, v)

array([14.,  5.,  5.])

In [24]:
U.dot(v)

array([14,  5,  5])

In [29]:
def matrix_matrix_mutiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_cols, num_cols))

    for i in range(num_cols):
        vi = U[:,i]
        Uvi = matric_vector_multiplication(U, vi)

        result[:, i] = Uvi
    return result


In [32]:
U.dot(V)

array([[ 2. , 14. , 13. ],
       [ 1. ,  4. ,  5. ],
       [ 3. ,  7.5,  9. ]])

In [34]:
I = np.eye(3)

In [35]:
V.dot(I)

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

# Inverse

In [39]:
Vs = V[[0, 1, 2]]
Vs

array([[1. , 1. , 2. ],
       [0. , 0.5, 1. ],
       [0. , 2. , 1. ]])

In [40]:
Vs_inv = np.linalg.inv(Vs)

In [41]:
Vs_inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

In [42]:
Vs.dot(Vs_inv)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])