In [1]:
import numpy as np

In [4]:
arr = np.zeros(10)

numpy.ndarray

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.full(10, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [8]:
a = np.array([1,2,3,4,5,7,12])

In [9]:
a

array([ 1,  2,  3,  4,  5,  7, 12])

In [11]:
a[2] = 10

In [12]:
a

array([ 1,  2, 10,  4,  5,  7, 12])

In [13]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
np.linspace(0,100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

## Multidimensional arrays

In [18]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [21]:
n[0,1]

np.int64(2)

In [24]:
n[0] = [1,1,1]

In [25]:
n

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
n[:,2] = [0,1,2]

In [32]:
n

array([[1, 1, 0],
       [4, 5, 1],
       [7, 8, 2]])

## Randomly generated arrays

In [49]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [50]:
np.random.seed(2)
100 * np.random.rand(5,2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [52]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5,2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

# Element-wise operations

In [55]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [57]:
a * 2

array([0, 2, 4, 6, 8])

In [61]:
b = (10 + (a * 2)) ** 2 / 100

In [62]:
a + b

array([1.  , 2.44, 3.96, 5.56, 7.24])

In [63]:
a + b / 2

array([0.5 , 1.72, 2.98, 4.28, 5.62])

## 

# Comparison operations

In [64]:
a < b

array([ True,  True, False, False, False])

In [65]:
a >= b

array([False, False,  True,  True,  True])

In [66]:
a[a>b]

array([2, 3, 4])

# Summarizing operations

In [67]:
a

array([0, 1, 2, 3, 4])

In [68]:
a.min()

np.int64(0)

In [69]:
a.sum()

np.int64(10)

In [70]:
a.mean()

np.float64(2.0)